server:
  protocol: http
  host: 127.0.0.1
  port: 7150

logger:
  level: debug
  format: json
  crates:
    - axum
    - service
  file_appender:
    enable: true
    non_blocking: true
    rotation: hourly
    filename_suffix: log
    max_log_files: 20

auth:
  access:
    public_key: secrets/keys/dev/access_key_pub.pem
    private_key: secrets/keys/dev/access_key.pem
    maxage: 900 # seconds 15 minutes
  refresh:
    public_key: secrets/keys/dev/refresh_key_pub.pem
    private_key: secrets/keys/dev/refresh_key.pem
    maxage: 604800 # seconds 7 days
  verification_token_expiry: 604800 # seconds 7 days
  refresh_token_expiry: 1800 # seconds 30 minutes
