server:
  protocol: http
  host: 127.0.0.1
  port: 7175

database:
  uri: postgresql://username:password@localhost:5432/database
  max_connections: 1
  min_connections: 1
  connection_timeout: 5
  idle_timeout: 5
  auto_migrate: true
  dangerously_truncate: false
  dangerously_recreate: true

redis:
  url: redis://127.0.0.1:6379/

logger:
  level: trace
  format: full
  crates:
    - axum
    - service

mailer:
  smtp:
    enable: true
    host: localhost
    port: 1025
    secure: false
    auth:
      # username:
      # password:

auth:
  access:
    public_key: secrets/keys/test/access_key_pub.pem
    private_key: secrets/keys/test/access_key.pem
    maxage: 900 # seconds 15 minutes
  refresh:
    public_key: secrets/keys/test/refresh_key_pub.pem
    private_key: secrets/keys/test/refresh_key.pem
    maxage: 604800 # seconds 7 days
  verification_token_expiry: 86400 # seconds 24 hours
  refresh_token_expiry: 900 # seconds 15 minutes
