/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainSettingsIndexRouteImport } from './routes/_main/settings/index'
import { Route as MainProductsIndexRouteImport } from './routes/_main/products/index'
import { Route as MainCategoriesIndexRouteImport } from './routes/_main/categories/index'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as MainProductsCreateIndexRouteImport } from './routes/_main/products/create/index'
import { Route as MainPeopleStaffIndexRouteImport } from './routes/_main/people/staff/index'
import { Route as MainPeopleCustomersIndexRouteImport } from './routes/_main/people/customers/index'
import { Route as MainCategoriesCreateIndexRouteImport } from './routes/_main/categories/create/index'
import { Route as MainAccessControlRolesIndexRouteImport } from './routes/_main/access-control/roles/index'
import { Route as MainAccessControlPermissionsIndexRouteImport } from './routes/_main/access-control/permissions/index'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProductsIndexRoute = MainProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCategoriesIndexRoute = MainCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_auth/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainProductsCreateIndexRoute = MainProductsCreateIndexRouteImport.update({
  id: '/products/create/',
  path: '/products/create/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPeopleStaffIndexRoute = MainPeopleStaffIndexRouteImport.update({
  id: '/people/staff/',
  path: '/people/staff/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPeopleCustomersIndexRoute =
  MainPeopleCustomersIndexRouteImport.update({
    id: '/people/customers/',
    path: '/people/customers/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainCategoriesCreateIndexRoute =
  MainCategoriesCreateIndexRouteImport.update({
    id: '/categories/create/',
    path: '/categories/create/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainAccessControlRolesIndexRoute =
  MainAccessControlRolesIndexRouteImport.update({
    id: '/access-control/roles/',
    path: '/access-control/roles/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainAccessControlPermissionsIndexRoute =
  MainAccessControlPermissionsIndexRouteImport.update({
    id: '/access-control/permissions/',
    path: '/access-control/permissions/',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/categories/': typeof MainCategoriesIndexRoute
  '/products/': typeof MainProductsIndexRoute
  '/settings/': typeof MainSettingsIndexRoute
  '/access-control/permissions/': typeof MainAccessControlPermissionsIndexRoute
  '/access-control/roles/': typeof MainAccessControlRolesIndexRoute
  '/categories/create/': typeof MainCategoriesCreateIndexRoute
  '/people/customers/': typeof MainPeopleCustomersIndexRoute
  '/people/staff/': typeof MainPeopleStaffIndexRoute
  '/products/create/': typeof MainProductsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/categories': typeof MainCategoriesIndexRoute
  '/products': typeof MainProductsIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/access-control/permissions': typeof MainAccessControlPermissionsIndexRoute
  '/access-control/roles': typeof MainAccessControlRolesIndexRoute
  '/categories/create': typeof MainCategoriesCreateIndexRoute
  '/people/customers': typeof MainPeopleCustomersIndexRoute
  '/people/staff': typeof MainPeopleStaffIndexRoute
  '/products/create': typeof MainProductsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_main/categories/': typeof MainCategoriesIndexRoute
  '/_main/products/': typeof MainProductsIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
  '/_main/access-control/permissions/': typeof MainAccessControlPermissionsIndexRoute
  '/_main/access-control/roles/': typeof MainAccessControlRolesIndexRoute
  '/_main/categories/create/': typeof MainCategoriesCreateIndexRoute
  '/_main/people/customers/': typeof MainPeopleCustomersIndexRoute
  '/_main/people/staff/': typeof MainPeopleStaffIndexRoute
  '/_main/products/create/': typeof MainProductsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/'
    | '/categories/'
    | '/products/'
    | '/settings/'
    | '/access-control/permissions/'
    | '/access-control/roles/'
    | '/categories/create/'
    | '/people/customers/'
    | '/people/staff/'
    | '/products/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/categories'
    | '/products'
    | '/settings'
    | '/access-control/permissions'
    | '/access-control/roles'
    | '/categories/create'
    | '/people/customers'
    | '/people/staff'
    | '/products/create'
  id:
    | '__root__'
    | '/_main'
    | '/_main/'
    | '/_auth/sign-in/'
    | '/_main/categories/'
    | '/_main/products/'
    | '/_main/settings/'
    | '/_main/access-control/permissions/'
    | '/_main/access-control/roles/'
    | '/_main/categories/create/'
    | '/_main/people/customers/'
    | '/_main/people/staff/'
    | '/_main/products/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/products/': {
      id: '/_main/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof MainProductsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/categories/': {
      id: '/_main/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof MainCategoriesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/products/create/': {
      id: '/_main/products/create/'
      path: '/products/create'
      fullPath: '/products/create/'
      preLoaderRoute: typeof MainProductsCreateIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/people/staff/': {
      id: '/_main/people/staff/'
      path: '/people/staff'
      fullPath: '/people/staff/'
      preLoaderRoute: typeof MainPeopleStaffIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/people/customers/': {
      id: '/_main/people/customers/'
      path: '/people/customers'
      fullPath: '/people/customers/'
      preLoaderRoute: typeof MainPeopleCustomersIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/categories/create/': {
      id: '/_main/categories/create/'
      path: '/categories/create'
      fullPath: '/categories/create/'
      preLoaderRoute: typeof MainCategoriesCreateIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/access-control/roles/': {
      id: '/_main/access-control/roles/'
      path: '/access-control/roles'
      fullPath: '/access-control/roles/'
      preLoaderRoute: typeof MainAccessControlRolesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/access-control/permissions/': {
      id: '/_main/access-control/permissions/'
      path: '/access-control/permissions'
      fullPath: '/access-control/permissions/'
      preLoaderRoute: typeof MainAccessControlPermissionsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainCategoriesIndexRoute: typeof MainCategoriesIndexRoute
  MainProductsIndexRoute: typeof MainProductsIndexRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
  MainAccessControlPermissionsIndexRoute: typeof MainAccessControlPermissionsIndexRoute
  MainAccessControlRolesIndexRoute: typeof MainAccessControlRolesIndexRoute
  MainCategoriesCreateIndexRoute: typeof MainCategoriesCreateIndexRoute
  MainPeopleCustomersIndexRoute: typeof MainPeopleCustomersIndexRoute
  MainPeopleStaffIndexRoute: typeof MainPeopleStaffIndexRoute
  MainProductsCreateIndexRoute: typeof MainProductsCreateIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainCategoriesIndexRoute: MainCategoriesIndexRoute,
  MainProductsIndexRoute: MainProductsIndexRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
  MainAccessControlPermissionsIndexRoute:
    MainAccessControlPermissionsIndexRoute,
  MainAccessControlRolesIndexRoute: MainAccessControlRolesIndexRoute,
  MainCategoriesCreateIndexRoute: MainCategoriesCreateIndexRoute,
  MainPeopleCustomersIndexRoute: MainPeopleCustomersIndexRoute,
  MainPeopleStaffIndexRoute: MainPeopleStaffIndexRoute,
  MainProductsCreateIndexRoute: MainProductsCreateIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
